### PR TITLE
/var/lib/ceph as btrfs subvolume with CoW disabled (bsc#1013011)

### PR DESCRIPTION
**Pull request by kmroz**
Signed-off-by: Karol Mroz <kmroz@suse.de>

### CODE REVIEW

**Comment by jreidinger** [comment]
it looks fine, but it should contain version increase and changes entry including bugzilla number for reference.

**Comment by kmroz** [comment]
@jreidinger - Thank you.  PR updated!

**Comment by jreidinger** [comment]
LGTM, just please fix conflict.

**Comment by kmroz** [comment]
@jreidinger - Rebased and conflict fixed.

**Comment by kmroz** [comment]
@jreidinger - ping... PR should be ready.

**Comment by lslezak** [comment]
Hm, it has not been merged and there are some conflicts again... :worried: 

- Is this still needed? Bug https://bugzilla.suse.com/show_bug.cgi?id=1013011 mentions some related fixes in DeepSea.
- This is SLED (Desktop) control file, is it the correct place? I'd rather expect it in SLES or in both. I cannot see any similar PR for SLES

@kmroz ?

**Comment by teclator** [comment]
Apart of @lslezak comment, it also seems that after #69 this PR does not make sense at all for the time being. @kmroz do you agree?

**Comment by teclator** [comment]
@kmroz @lslezak closing it by now. Feel free to reopen it if you consider it is still needed.

**Pull request closed without merging**
